server:
  port: ${PORT:8080}

spring:
  application:
    name: cheapest-travel
  cloud:
    kubernetes:
      config:
        enabled: true
      secrets:
        enabled: true
      reload:
        enabled: true
        strategy: restart_context
management:
  endpoints:
    web:
      exposure:
        include: ["info","health","configprops","metrics","restart"]
  endpoint:
    restart:
      enabled: true
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.9,0.95,0.99
      slo:
        http.server.requests: 100ms, 150ms, 200ms, 300ms
