server:
  port: ${PORT:8080}
spring:
  application:
    name: cheapest-travel
management:
  endpoints:
    web:
      exposure:
        include: ["info","health","prometheus","metrics"]
  endpoint:
    health:
      show-details: always
