apiVersion: v1
kind: ConfigMap
metadata:
  name: cheapest-travel-cm
data:
  application.yml: |-

    spring:
      application:
        name: cheapest-travel
    management:
      endpoints:
        web:
          exposure:
            include: ["info","health","metrics"]
      endpoint:
        health:
          show-details: always

  log4j2.yml: |-

    Configuration:
      name: PropertiesConfig
      status: DEBUG
      dest: err

      Appenders:
        Console:
          name: ConsoleAppender
          target: SYSTEM_OUT
          PatternLayout:
            pattern: "[%d{dd-MM-yyyy HH:mm:ss.SSS}] %highlight{[%-5level]} [%t] %highlight{%c{1}} - %msg%n%throwable"

      Loggers:
        Root:
          level: error
          AppenderRef:
          - ref: ConsoleAppender

        Logger:
        - name:  br.com.booking.travel
          additivity: false
          level: info
          AppenderRef:
          - ref: ConsoleAppender
            level: info